nombre = input("Ingrese su Nombre: ")
apellido = input("Ingrese su Apellido: ")
Seccion = input("Ingrese su Seccion: ")
Sede = input("Ingrese su Sede: ")
print("----------------------------------------")
print("Informacion ingresada:")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("Sede:", Sede)
print("Seccion:", Seccion)
